spring.application.name=api-rest-spring-boot

spring.datasource.url=jdbc:h2:mem:lib84
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.web.resources.add-mappings=true

spring.h2.console.settings.web-allow-others=true
spring.mvc.pathmatch.use-suffix-pattern=true

# ── Swagger / SpringDoc ──
springdoc.version=1.0.0
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.display-request-duration=true
#springdoc.swagger-ui.default-models-expand-depth=-1


